### ISSUE TITLE
The issue of loading .pkl files

### ISSUE THREAD

**Issue by DorisxinDU** [rajpurkarlab/cheXlocalize#10] opened 2022-08-16 19:45 UTC
I meet the following problem while running heatmap_to_segmetation.ipynb on jupyter notebook. Please can you help me.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_58474/3145830382.py in <module>
    227         "`if_smoothing` flag must be either `True` or `False`"
    228 
--> 229     heatmap_to_mask(args)
    230 #  args = easydict.EasyDict({
    231 #     "":,

/tmp/ipykernel_58474/3145830382.py in heatmap_to_mask(args)
    171                                    prob_cutoff=prob_cutoff,
    172                                    smoothing=eval(args.if_smoothing),
--> 173                                    k=args.k)
    174         encoded_mask = encode_segmentation(segmentation)
    175 

/tmp/ipykernel_58474/3145830382.py in pkl_to_mask(pkl_path, threshold, prob_cutoff, smoothing, k)
    104     print(pkl_path)
    105 #     info=torch.load(pkl_path,map_location=torch.device('cpu'))
--> 106     info = CPU_Unpickler(open(pkl_path, 'rb')).load()
    107 
    108     # get saliency map and resize

TypeError: argument list must be a tuple

**Comment by asaporta** [comment] 2022-08-16 19:56
Hi @DorisxinDU,

Which inputs are you using? And is this just a jupyter notebook that you created on your own from our `heatmap_to_segmentation.py` python script?

**Comment by DorisxinDU** [comment] 2022-08-16 20:31
> Hi @DorisxinDU,
> 
> Which inputs are you using? And is this just a jupyter notebook that you created on your own from our `heatmap_to_segmentation.py` python script?

the "map_dir" is "sample/gradcam_maps_val/"which is provided by you. Yep the jupyter notebook is converted from your python script.

**Comment by asaporta** [comment] 2022-08-16 21:15
Hm, it seems to be running alright when I run the python script. Is it possible that the problem is that `if_smoothing` isn't set in your notebook? (In the Python script, there's a default value set by `argparse`.)

**Comment by DorisxinDU** [comment] 2022-08-17 16:11
I tried the python script, the same error is given. Please see the below picture.

![image](https://user-images.githubusercontent.com/42578990/185189760-cfcbf90e-6312-40cc-84ad-cdfcef239f88.png)

**Comment by asaporta** [comment] 2022-08-17 23:17
hmm...is it possible to put a breakpoint before line 105 and see what `pkl_path` is? It should look something like this:
`PosixPath('sample/gradcam_maps_val/patient64542_study1_view1_frontal_Suppo
rt Devices_map.pkl')`

**Comment by asaporta** [comment] 2022-08-17 23:23
oh, it looks like you haven't specified `map_dir`, which is a required flag! Our [README](https://github.com/rajpurkarlab/cheXlocalize) specifies which flags are required and which are optional for all scripts in the repo.

**Comment by DorisxinDU** [comment] 2022-08-18 14:32
> oh, it looks like you haven't specified `map_dir`, which is a required flag! Our [README](https://github.com/rajpurkarlab/cheXlocalize) specifies which flags are required and which are optional for all scripts in the repo.

I gave default values to all arguments needed. And the pkl_path is shown below.
![2022-08-18 (3)](https://user-images.githubusercontent.com/42578990/185421078-9470b00d-e863-43c1-bb6b-e8460d4ac992.png)

**Comment by asaporta** [comment] 2022-08-19 20:02
I'm so sorry, it's tough for me to debug this remotely, and we're having a hard time reproducing your bug on our end. Is it possible you need a `.` before `/datasets/` in the `pkl_path`? These Grad-CAM pickle files aren't on GPUs, so you could also just avoid using the `CPU_Unpickler()` entirely, and see if that helps? For example, you could use `pickle.load()`.

**Comment by asaporta** [comment] 2022-10-14 16:42
I'm going to close this issue for now, but feel free to reach out if you're still having problems!

**Closed as completed by asaporta** 2022-10-14 16:42 UTC
